import { Product, Category, Review, FAQ } from './types';

export const categories: Category[] = [
  {
    id: 'birthday',
    name: 'Birthday',
    iconName: 'Cake',
    description: 'Celebrate milestones with sweetness and joy.',
    itemCount: 42,
  },
  {
    id: 'anniversary',
    name: 'Anniversary',
    iconName: 'Heart',
    description: 'Keep the spark glowing with curated romance.',
    itemCount: 28,
  },
  {
    id: 'wedding',
    name: 'Wedding',
    iconName: 'Sparkles',
    description: 'Elegant keepsakes for their happily ever after.',
    itemCount: 35,
  },
  {
    id: 'holidays',
    name: 'Holidays',
    iconName: 'Calendar',
    description: 'Festive collections to spread warmth and cheer.',
    itemCount: 19,
  },
  {
    id: 'corporate',
    name: 'Corporate',
    iconName: 'Briefcase',
    description: 'Sophisticated standard-defining professional tokens.',
    itemCount: 24,
  },
  {
    id: 'new-arrivals',
    name: 'New Arrivals',
    iconName: 'Gift',
    description: 'The freshest curation of modern thoughtfulness.',
    itemCount: 15,
  },
  {
    id: 'deals',
    name: 'Deals',
    iconName: 'Percent',
    description: 'Curated gestures of love at delightful values.',
    itemCount: 12,
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Premium Gift Hamper',
    description: 'A luxurious gift basket featuring Belgian chocolates, custom hand-poured lavender soy candle, artisanal greeting card, and two ceramic mugs.',
    price: 34.99,
    originalPrice: 45.00,
    rating: 4.9,
    reviewsCount: 128,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=600',
    category: 'anniversary',
    tag: 'Best Seller',
    isAvailable: true,
    type: 'baskets',
  },
  {
    id: 'prod-2',
    name: 'Crimson Rose Velvet Bouquet',
    description: '24 premium fresh-cut long-stemmed deep red roses, hand-tied in premium dark matte wrapping with gold-embossed silk ribbon.',
    price: 49.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviewsCount: 86,
    image: 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&q=80&w=600',
    category: 'anniversary',
    tag: 'New',
    isAvailable: true,
    type: 'flowers',
  },
  {
    id: 'prod-3',
    name: 'LED Infinity Photo Frame',
    description: 'A personalized wooden-acrylic photo frame backlit with warm fairy LED lights to illuminate your special shared memories.',
    price: 29.99,
    rating: 4.7,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=600',
    category: 'birthday',
    tag: 'Popular',
    isAvailable: true,
    type: 'other',
  },
  {
    id: 'prod-11',
    name: 'Classic Belgian Chocolate Fudge Cake',
    description: 'A rich, decadent double-layered chocolate fudge cake coated in dense dark chocolate ganache, topped with handmade truffles.',
    price: 38.00,
    originalPrice: 48.00,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
    category: 'birthday',
    tag: 'Best Seller',
    isAvailable: true,
    type: 'cakes',
  },
  {
    id: 'prod-12',
    name: 'Red Velvet Majestic Rose Cake',
    description: 'A beautiful anniversary special red velvet sponge cake layered with rich cream cheese frosting and adorned with real crystallized edible rose petals.',
    price: 42.00,
    rating: 4.8,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1616260841585-0422ec04e7b0?auto=format&fit=crop&q=80&w=600',
    category: 'anniversary',
    tag: 'New',
    isAvailable: true,
    type: 'cakes',
  },
  {
    id: 'prod-13',
    name: 'Artisanal Pastel Macaron Assortment',
    description: 'A gift box of 12 delicate French macarons filled with chocolate ganache, vanilla bean, salted caramel, and fresh raspberry coulis.',
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.9,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=600',
    category: 'new-arrivals',
    tag: 'Popular',
    isAvailable: true,
    type: 'sweets',
  },
  {
    id: 'prod-14',
    name: 'Luxury Salted Caramel & Gold Truffles',
    description: 'Handcrafted sea salt dark chocolate caramels and milk chocolate hazelnut pralines, dusted in 24K edible gold leaf.',
    price: 22.00,
    rating: 4.7,
    reviewsCount: 54,
    image: 'https://images.unsplash.com/photo-1548907040-4d42b521251c?auto=format&fit=crop&q=80&w=600',
    category: 'corporate',
    tag: 'New',
    isAvailable: true,
    type: 'sweets',
  },
  {
    id: 'prod-4',
    name: 'Executive Minimalist Gift Set',
    description: 'A professional set including a premium vegan leather wallet, a heavy-gauge ballpoint pen, and a matching key organizer.',
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.6,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600',
    category: 'corporate',
    isAvailable: true,
    type: 'other',
  },
  {
    id: 'prod-5',
    name: 'Cute Crimson Hug Bear',
    description: 'Ultra-soft fluffy teddy bear holding a velvet heart pillow, dressed in a red satin bow. Perfectly sweet for birthdays.',
    price: 19.99,
    rating: 4.9,
    reviewsCount: 73,
    image: 'https://images.unsplash.com/photo-1559251606-c623743a6d76?auto=format&fit=crop&q=80&w=600',
    category: 'birthday',
    tag: 'Best Seller',
    isAvailable: true,
    type: 'other',
  },
  {
    id: 'prod-6',
    name: 'Eternal 24K Gold Rose',
    description: 'A natural preserved rose meticulously dipped in pure 24-karat gold, resting in a luxury velvet presentation case.',
    price: 79.99,
    originalPrice: 95.00,
    rating: 5.0,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=600',
    category: 'wedding',
    tag: 'Limited',
    isAvailable: true,
    type: 'flowers',
  },
  {
    id: 'prod-7',
    name: 'Organic Scented Candle Trio',
    description: 'Three hand-poured soy wax candles with premium fragrances: Sea Salt & Sage, Amber Oud, and French Jasmine.',
    price: 24.99,
    rating: 4.7,
    reviewsCount: 51,
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&q=80&w=600',
    category: 'new-arrivals',
    isAvailable: true,
    type: 'baskets',
  },
  {
    id: 'prod-8',
    name: 'Champagne & Gold Truffle Basket',
    description: 'A celebratory hamper including premium sparkling grape beverage, a box of luxury gold-leaf chocolate truffles, and flute glasses.',
    price: 64.99,
    originalPrice: 79.99,
    rating: 4.9,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&q=80&w=600',
    category: 'holidays',
    tag: 'Popular',
    isAvailable: true,
    type: 'baskets',
  },
  {
    id: 'prod-9',
    name: 'Festive Gingerbread Joy Hamper',
    description: 'Holiday special gingerbread assortment, cocoa mix, handmade marshmallows, and a gorgeous limited-edition crimson holiday ceramic mug.',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.8,
    reviewsCount: 22,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?auto=format&fit=crop&q=80&w=600',
    category: 'holidays',
    tag: 'Limited',
    isAvailable: true,
    type: 'baskets',
  },
  {
    id: 'prod-10',
    name: 'Rose Quartz Eternal Ring Box',
    description: 'A beautiful natural pink rose quartz ring box handcrafted with brass trim, featuring silk lining to hold everlasting vows.',
    price: 45.00,
    rating: 4.9,
    reviewsCount: 15,
    image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&q=80&w=600',
    category: 'wedding',
    tag: 'New',
    isAvailable: true,
    type: 'other',
  }
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    name: 'Amara Khan',
    location: 'Lahore',
    rating: 5,
    comment: 'The Premium Gift Hamper was absolutely stunning! The lavender candle smells heaven-like and the presentation was extremely modern. Highly recommended!',
    date: 'June 15, 2026',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
  },
  {
    id: 'rev-2',
    name: 'Zayn Malik',
    location: 'Karachi',
    rating: 5,
    comment: 'I ordered the Crimson Rose bouquet for my wife. The roses were so fresh and lasted more than a week. The premium black wrapping is incredibly sophisticated.',
    date: 'May 28, 2026',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120',
  },
  {
    id: 'rev-3',
    name: 'Sarah Ahmed',
    location: 'Islamabad',
    rating: 4,
    comment: 'The LED Photo Frame made the perfect anniversary gift. The warm lights add such a cosy feeling to our room. Safe packaging and delivered on time!',
    date: 'June 20, 2026',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=120',
  },
];

export const faqs: FAQ[] = [
  {
    id: 'faq-1',
    question: 'How do I customize my gift or add a personalized greeting card?',
    answer: 'Once you select a gift and add it to your cart, you can check the "Add Personalized Card" option directly in the Cart Drawer. You can type in your custom message, and we will elegantly handwrite it onto a premium floral-themed greeting card included with your order free of cost!',
  },
  {
    id: 'faq-2',
    question: 'What are your shipping and delivery timelines?',
    answer: 'We provide Free Standard Delivery for all orders over $30.00. Standard delivery takes 2-4 business days. For urgent occasions, we offer Same-Day Express Delivery in major metropolitan cities for an additional fee of $5.99 (orders must be placed before 2:00 PM).',
  },
  {
    id: 'faq-3',
    question: 'Do you offer premium gift-wrapping services?',
    answer: 'Absolutely! Every single order from our store comes standard in our signature luxury gift box with a silk ribbon. You can also select customized wrap themes (such as Crimson Velvet, Golden Elegance, or Festive Floral) during checkout for that extra touch.',
  },
  {
    id: 'faq-4',
    question: 'Can I track my order live after shipping?',
    answer: 'Yes! As soon as your gift is dispatched, you will receive an automated email and SMS notification containing a direct link to our live GPS tracking dashboard, allowing you to see exactly when your loved one will receive their surprise.',
  },
  {
    id: 'faq-5',
    question: 'What is your return and cancellation policy?',
    answer: 'We want your gifting experience to be completely worry-free. You can cancel your order at any time before it enters the shipping phase for a 100% full refund. For non-customized gifts, we offer a hassle-free 14-day return and exchange window if the item is in its original pristine condition.',
  },
];

export const heroSlides = [
  {
    id: 'slide-1',
    title: 'Gifts From the Heart',
    subtitle: 'Crimson Rose Velvet Bouquet',
    description: 'Fresh, premium crimson roses hand-tied in premium gold-embossed velvet wrap to express profound emotion, adoration, and sweet celebrations.',
    price: 49.99,
    unit: 'Bouquet',
    rating: 4.8,
    reviewsCount: 325,
    image: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&q=80&w=800',
    colorTheme: 'from-[#FFF0F2] to-[#FFE4E8]',
    accentColor: '#f43f5e',
    productId: 'prod-2',
  },
  {
    id: 'slide-2',
    title: 'The Ultimate Surprise',
    subtitle: 'Premium Artisan Gift Hamper',
    description: 'An exquisitely curated selection of luxury Belgian chocolates, hand-poured lavender soy wax candles, and ceramic mugs in our signature velvet box.',
    price: 34.99,
    unit: 'Hamper Set',
    rating: 4.9,
    reviewsCount: 198,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=800',
    colorTheme: 'from-[#FAF6F0] to-[#F1E8DC]',
    accentColor: '#B48A4E',
    productId: 'prod-1',
  },
  {
    id: 'slide-3',
    title: 'Illuminated Ambiance',
    subtitle: 'LED Infinity Memory Frame',
    description: 'Your favorite memories carved in custom high-density wooden frame, beautifully illuminated by romantic warm micro-LED string lights.',
    price: 29.99,
    unit: 'Frame',
    rating: 4.7,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800',
    colorTheme: 'from-[#F3F4F6] to-[#E5E7EB]',
    accentColor: '#374151',
    productId: 'prod-3',
  },
];
